// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/sloane": {
    params: {};
  };
  "/clive": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/sloane" | "/clive";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./sloanecol/sloanecol.tsx": {
    id: "sloanecol/sloanecol";
    page: "/sloane";
  };
  "./clivecol/clivecol.tsx": {
    id: "clivecol/clivecol";
    page: "/clive";
  };
};