// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/sloane": {
    params: {};
  };
  "/sloane-new": {
    params: {};
  };
  "/sloane-new/:objectIndex": {
    params: {
      "objectIndex": string;
    };
  };
  "/clive": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/sloane" | "/sloane-new" | "/sloane-new/:objectIndex" | "/clive";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./sloanecol/sloanecol.tsx": {
    id: "sloanecol/sloanecol";
    page: "/sloane";
  };
  "./sloanecol/sloanecol-new.tsx": {
    id: "sloanecol/sloanecol-new";
    page: "/sloane-new";
  };
  "./object-page.tsx": {
    id: "object-page";
    page: "/sloane-new/:objectIndex";
  };
  "./clivecol/clivecol.tsx": {
    id: "clivecol/clivecol";
    page: "/clive";
  };
};